spring:
  mail:
    host: smtp.gmail.com
    username: SOJAZFitness@gmail.com
    password: Capstone22
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
